const $=s=>document.querySelector(s);
const screens=['dump','challenge','memory'];
let state={raw:'',questions:[],idx:0,answers:[],open:[]};
const categories=['Role / Responsibility','Key People','Decision Authority','Approvals','Dependencies','Normal Workflows','Exceptions','Escalation Paths','External Relationships','Preferences','Open Questions'];
function show(id){screens.forEach(s=>$('#'+s).classList.toggle('active',s===id));window.scrollTo({top:0,behavior:'smooth'})}
function sentences(t){return t.replace(/\n+/g,' ').split(/(?<=[.!?])\s+|;\s+/).map(x=>x.trim()).filter(x=>x.length>8)}
function names(s){const stop=new Set(['Marketing','Finance','Legal','HR','The','When','If','Normally','Usually','Sometimes','Larger','Smaller','Most','One','Our','My','We','They','You','Project','Product']);return [...new Set((s.match(/\b[A-Z][a-z]{2,}\b/g)||[]).filter(n=>!stop.has(n)))]}
function buildQuestions(text){const ss=sentences(text), q=[], seen=new Set(); const add=(type,src,question,why,priority=1)=>{let k=question.toLowerCase();if(!seen.has(k)){seen.add(k);q.push({type,src,question,why,priority})}};
 for(const s of ss){const low=s.toLowerCase(); const ns=names(s);
  if(/\b(normally|usually|generally|typically|most of the time)\b/.test(low)) add('Exception',s,`You said “${s.match(/normally|usually|generally|typically|most of the time/i)[0]}”. When does that normal rule not apply?`,'“Normally” implies an exception that the next person may need to recognise.',5);
  if(/\b(urgent|urgently|asap|critical|emergency)\b/.test(low)) add('Threshold',s,'What specifically makes this “urgent”, and who has authority to make that call?','Urgency changes behaviour, but the trigger and authority are not yet explicit.',5);
  if(/\b(large|larger|big|major|small|smaller|significant|high[- ]value|low[- ]value)\b/.test(low)) add('Threshold',s,'You described a size or importance threshold. What is the practical cutoff, and what changes once it is crossed?','A threshold is only actionable when the next person can recognise it.',5);
  if(/\b(approve|approval|sign.?off|review|look at|check)\b/.test(low)) add('Approval',s,ns.length?`You mentioned ${ns[0]} in a review or approval context. What exactly can ${ns[0]} decide: the work itself, budget, timing, or something else?`:'You mentioned a review or approval. Is it mandatory, who has final authority, and what exactly are they approving?','Review, advice and approval are operationally different.',4);
  if(/\b(before|after|depends on|dependent|once|until|then)\b/.test(low)) add('Dependency',s,'What must be true before this step can happen, and what do you do if that dependency is late or missing?','The sequence is visible, but the failure path is not.',4);
  if(/\b(if|unless|except|skip|bypass|without)\b/.test(low)) add('Exception',s,'You described a conditional or exception. Who is allowed to use it, and is it an accepted rule or just a working habit?','Exceptions can become risky if authority and legitimacy are unclear.',4);
  if(/\b(escalat|stuck|blocked|delay|fails|goes wrong|problem)\b/.test(low)) add('Escalation',s,'When the normal process fails here, who is the first escalation point—and what would make you escalate further?','A usable handover needs the failure path, not only the normal path.',5);
  if(/\b(prefer|likes|doesn't like|does not like|less formal|informal|formal)\b/.test(low)) add('Preference',s,'Is that a formal organisational rule or a stakeholder preference? What happens if the next person handles it differently?','Preferences should not be mistaken for policy.',3);
  if(ns.length) for(const n of ns.slice(0,2)) add('Relationship',s,`You mentioned ${n}. Why is ${n} involved here, and when should the next person contact them directly?`,'A name is useful only when the relationship and trigger are clear.',2);
  if(/\b(responsible|own|owns|handle|handles|manage|manages|lead|leads)\b/.test(low) && !ns.length) add('Responsibility',s,'Who owns the outcome here, rather than simply doing part of the work?','Execution responsibility and outcome ownership may be different.',3);
 }
 if(!q.length){const s=ss[0]||text;add('Uncertainty',s,'What part of what you just described would be easiest for a new person to misunderstand or act on incorrectly?','The handover contains context, but no explicit operational trigger was detected.',3)}
 return q.sort((a,b)=>b.priority-a.priority).slice(0,7)
}
function start(){let t=$('#dumpInput').value.trim();if(t.length<20){alert('Give me a little more context first — a few natural sentences is enough.');return}state={raw:t,questions:buildQuestions(t),idx:0,answers:[],open:[]};show('challenge');renderQ()}
function renderQ(){if(state.idx>=state.questions.length){renderMemory();show('memory');return}const q=state.questions[state.idx];$('#qCount').textContent=`Question ${state.idx+1} of ${state.questions.length}`;$('#progressBar').style.width=`${((state.idx+1)/state.questions.length)*100}%`;$('#sourceQuote').textContent=q.src;$('#questionText').textContent=q.question;$('#whyText').textContent=`Why this matters: ${q.why}`;$('#answerInput').value='';$('#answerInput').focus()}
function answer(skip=false){const q=state.questions[state.idx],a=$('#answerInput').value.trim();if(!skip&&!a){alert('Answer naturally, or leave this question open.');return}if(skip)state.open.push({...q,answer:null});else state.answers.push({...q,answer:a});state.idx++;renderQ()}
function extract(){const out=Object.fromEntries(categories.map(c=>[c,[]])); const all=[...sentences(state.raw),...state.answers.map(x=>x.answer)];
 all.forEach(s=>{let low=s.toLowerCase(), ns=names(s);if(ns.length)out['Key People'].push(s);if(/approve|approval|sign.?off|review|look at|check/.test(low))out['Approvals'].push(s);if(/decid|authority|final call|override/.test(low))out['Decision Authority'].push(s);if(/before|after|depends|once|until|then/.test(low))out['Dependencies'].push(s);if(/normally|usually|generally|typically|process|workflow|every|each/.test(low))out['Normal Workflows'].push(s);if(/if|unless|except|skip|bypass|without|not apply/.test(low))out['Exceptions'].push(s);if(/escalat|stuck|blocked|delay|fails|goes wrong|problem/.test(low))out['Escalation Paths'].push(s);if(/agency|vendor|client|customer|partner|supplier|external/.test(low))out['External Relationships'].push(s);if(/prefer|likes|less formal|informal|formal/.test(low))out['Preferences'].push(s);if(/responsib|own|handle|manage|lead|role|project/.test(low))out['Role / Responsibility'].push(s)});
 state.answers.forEach(x=>{let map={Threshold:'Decision Authority',Relationship:'Key People',Responsibility:'Role / Responsibility',Approval:'Approvals',Dependency:'Dependencies',Exception:'Exceptions',Escalation:'Escalation Paths',Preference:'Preferences',Uncertainty:'Open Questions'};out[map[x.type]||'Open Questions'].push(x.answer)});state.open.forEach(x=>out['Open Questions'].push(x.question));for(const k in out)out[k]=[...new Set(out[k])].slice(0,5);return out}
function renderMemory(){const data=extract();const unresolved=state.open.length;const answered=state.answers.length;const score=Math.max(35,Math.min(92,Math.round(55+(answered/(answered+unresolved||1))*30 + Math.min(7,state.questions.length))));$('#readyScore').textContent=score+'%';$('#gapBanner').innerHTML=unresolved?`<strong>${unresolved} unresolved knowledge gap${unresolved>1?'s':''}</strong> · These remain open rather than being guessed.`:`<strong>No challenged questions left unanswered.</strong> The memory can still contain unknown gaps; this score does not claim completeness.`;
 $('#memoryGrid').innerHTML=categories.map(c=>`<div class="memory-card"><h3>${c}</h3>${data[c].length?`<ul>${data[c].map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:`<div class="empty">Not established in this conversation.</div>`}<div class="confidence">Confidence: ${data[c].length?(c==='Open Questions'?'Open':'Conversation-supported'):'Not established'}</div></div>`).join('');
 const val=state.answers.filter(x=>['Approval','Threshold','Exception','Escalation'].includes(x.type)).slice(0,3);$('#validationCards').innerHTML=(val.length?val:state.answers.slice(0,2)).map((x,i)=>`<div class="validation-card" data-i="${i}"><p>${escapeHtml(x.answer)}</p><span class="tag">${x.type}</span><div class="actions"><button onclick="validateCard(this,'Confirmed')">Confirm</button><button onclick="validateCard(this,'Needs correction')">Correct</button><button onclick="validateCard(this,'Clarification requested')">Request clarification</button></div></div>`).join('')||'<div class="empty">Answer a challenged rule to see targeted validation.</div>'}
function validateCard(btn,status){const card=btn.closest('.validation-card');card.querySelector('.actions').innerHTML=`<span class="tag">Manager: ${status}</span>`}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exportMemory(){const data=extract();const payload={prototype:'Living Role Memory v0.1',created:new Date().toISOString(),source_handover:state.raw,clarifications:state.answers.map(x=>({gap_type:x.type,question:x.question,answer:x.answer,trace:x.src})),unresolved:state.open.map(x=>({gap_type:x.type,question:x.question,trace:x.src})),role_memory:data,note:'Prototype output. Conversation-supported, not manager-validated organisational truth.'};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='living-role-memory.json';a.click();URL.revokeObjectURL(a.href)}
$('#startBtn').onclick=start;$('#answerBtn').onclick=()=>answer(false);$('#skipBtn').onclick=()=>answer(true);$('#restartBtn').onclick=()=>{state={raw:'',questions:[],idx:0,answers:[],open:[]};$('#dumpInput').value='';show('dump')};$('#exportBtn').onclick=exportMemory;$('#demoBtn').onclick=()=>{$('#dumpInput').value='Marketing normally goes through Michelle. Larger campaigns need Rachel to look at them. If something is urgent, we sometimes skip the usual Finance review. Our PR agency is less formal, so I usually message David directly when a launch is at risk. Legal approval needs to happen before the final launch date is confirmed.'};
